name: Binary Release

on:
  workflow_dispatch: 
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Binary
        run: |
          # Your build commands here
          ./build.sh RELEASE

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }} | cut -c1-7          
          release_name: ${{ github.sha }} | cut -c1-7
          draft: false
          prerelease: false

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: generate-random-tree-linux-amd64
          path: ./release/generate-random-tree

      - name: Attach Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./generate-random-tree-linux-amd64
          asset_name: generate-random-tree
          asset_content_type: application/octet-stream

